# Generated by Django 2.0.13 on 2020-07-03 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_validate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_admin', models.IntegerField(default=0)),
                ('photo_admin', models.IntegerField(default=0)),
                ('paper_admin', models.IntegerField(default=0)),
                ('face_admin', models.IntegerField(default=0)),
                ('real_admin', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_info', models.IntegerField(default=0)),
                ('profile_photo', models.IntegerField(default=0)),
                ('profile_paper', models.IntegerField(default=0)),
                ('profile_face', models.IntegerField(default=0)),
                ('profile_real', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
