# Generated by Django 3.0.8 on 2020-07-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_validate', '0004_checkstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='flag_type',
            field=models.IntegerField(choices=[(0, 'basic_profile'), (1, 'profile_photo'), (2, 'val_paper'), (3, 'val_beauty'), (4, 'val_noFilter')], default=0),
        ),
    ]
