# Generated by Django 3.0.8 on 2020-07-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_validate', '0005_auto_20200718_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='admin',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
