# Generated by Django 3.0.8 on 2020-07-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_validate', '0006_auto_20200718_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='admin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
