# Generated by Django 3.0.8 on 2020-07-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_validate', '0007_auto_20200718_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='validate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
