# Generated by Django 3.0.8 on 2020-07-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_validate', '0009_auto_20200719_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='reason',
            field=models.IntegerField(choices=[(0, ' '), (1, '실물인증 실패'), (2, '얼굴확인 불가'), (3, '영상 오류')], default=0),
        ),
    ]
