# Generated by Django 3.0.8 on 2020-07-20 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_validate', '0010_auto_20200719_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='reason',
            field=models.IntegerField(choices=[(0, '--선택해주세요--'), (1, '실물인증 실패'), (2, '얼굴확인 불가'), (3, '영상 오류')], default=0),
        ),
        migrations.CreateModel(
            name='ValidatedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.BooleanField(default=False)),
                ('noFilter', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='image/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_validate.UserProfile')),
            ],
        ),
    ]
