# Generated by Django 3.0.8 on 2020-07-20 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_validate', '0011_auto_20200720_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='validate',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ValidatedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_validate.UserProfile')),
            ],
        ),
    ]
