# Generated by Django 3.0.8 on 2020-07-20 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_validate', '0012_auto_20200720_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('scored_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giver', to='profile_validate.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='profile_validate.UserProfile')),
            ],
        ),
    ]
