# Generated by Django 3.0.8 on 2020-07-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_validate', '0015_auto_20200721_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatedprofile',
            name='holiday',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validatedprofile',
            name='interest',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validatedprofile',
            name='introduce',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validatedprofile',
            name='trip',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
